### ISSUE TITLE
Remove the empty string in the end of the output file

### ISSUE THREAD

**Issue by akp6031** [lh3/ropebwt2#7]
Hi, if the repo is still being managed, I would humbly like to ask for removing the new line(\n) attached in the end of bwt output files.

Due to the glitch, succinct strings (e.g. wavelet tree) generated from the file have the empty symbol in the front of the rank, distorting the whole context.

Thank you!

**Comment by lh3** [comment]
This is intended. Please remove the trailing new line by yourself with something like `tr -d '\n'`
