### ISSUE TITLE
The basic command outputs wrong result. 

### ISSUE THREAD

**Issue by akp6031** [lh3/ropebwt2#8]
For the attached file with symbols below:
G (51374), C (35983), A (33513), T (32130)
[SRR20044276.part_001.part_001.fastq.gz](https://github.com/lh3/ropebwt2/files/12704578/SRR20044276.part_001.part_001.fastq.gz)

Running the command  prints the weird result that A:T and C:G share the same frequencies and wrong.
The output file is consistent with the printed result.
```
./ropebwt2 -o out.bwt SRR20044276.part_001.part_001.fastq 

symbol counts: ($, A, C, G, T, N) = (2000, 64643, 86357, 86357, 64643, 0)
```

I am receiving such similar results for any input.
Could I be advised for the practice?

**Comment by lh3** [comment]
`-R`
